mysql:
  host: ${oc.env:MYSQL_HOST,localhost}
  port: ${oc.env:MYSQL_PORT,3306}
  user: ${oc.env:MYSQL_USER,root}
  password: ${oc.env:MYSQL_DB_PWD,secret}
  database: ${oc.env:MYSQL_DB_NAME,myapp}
  charset: utf8mb4

# redis:
#   host: ${oc.env:REDIS_HOST,localhost}
#   port: ${oc.env:REDIS_PORT,6379}
#   password: ${oc.env:REDIS_PASSWORD,null}
#   db: ${oc.env:REDIS_DB,0}
#   ssl: ${oc.env:REDIS_SSL,False}

# elasticsearch:
#   hosts: ${oc.env:ES_HOSTS,localhost}
#   port: ${oc.env:ES_PORT,9200}
#   use_ssl: ${oc.env:ES_USE_SSL,False}
#   verify_certs: ${oc.env:ES_VERIFY_CERTS,True}
#   username: ${oc.env:ES_USERNAME,null}
#   password: ${oc.env:ES_PASSWORD,null}