version: 1
disable_existing_loggers: false
formatters:
  verbose:
    class: 'logging.Formatter'
    format: '%(asctime)s; %(levelname)-8s; [%(process)d - %(thread)s]; %(name)-35s; %(filename)-20s;%(funcName)-20s;%(lineno)4d: %(message)s'
handlers:
  console:
    class: 'logging.StreamHandler'
    formatter: 'verbose'
    stream : 'ext://sys.stdout'
root:
  level: 'INFO'
  handlers:
    - 'console'